Implementa a searchBar na homeViewController
devpass-tech/challenge-delivery-app pull request #21
Opened 2022-04-25 21:28 UTC by tandersonf

2022-04-26 15:02 UTC, ananogal requested changes

2022-04-26 15:02 UTC, ananogal commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +class HomeViewController: UIViewController, UISearchResultsUpdating {
```suggestion
class HomeViewController: UIViewController {
```
O que vc acha de criar antes uma extenção:
```
extension HomeViewController: UISearchResultsUpdating {}
```
Vc precisa de conformar com esse protocol? Ou com o `UISearchBarDelegate`

2022-04-26 15:02 UTC, ananogal commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +       let searchController = UISearchController(searchResultsController: nil)
```suggestion
       let searchController = UISearchController()
```

2022-04-26 15:02 UTC, ananogal commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +    lazy var searchController: UISearchController = {
Muito bem, usando `lazy var` 👍

2022-04-26 15:02 UTC, ananogal commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +        searchController.searchResultsUpdater = self
hummm 🤔 .... Aqui não deveríamos usar antes:
```suggestion
        searchController.searchBar.delegate = self
```

2022-04-26 15:02 UTC, ananogal commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +        navigationItem.title = "Delivery App"
hum 🤔 ... se calhar aquí passava essa configuração de `UI` para o `viewDidLoad`... assim ficam as configurações todas juntas no mesmo sitio e temos a certeza que já temos o `UI` inicializado

2022-04-26 19:23 UTC, tandersonf commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +class HomeViewController: UIViewController, UISearchResultsUpdating {
corrigido.

2022-04-26 19:24 UTC, tandersonf commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +       let searchController = UISearchController(searchResultsController: nil)
corrigido.

2022-04-26 19:24 UTC, tandersonf commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +        searchController.searchResultsUpdater = self
corrigido.

2022-04-26 19:24 UTC, tandersonf commented on solutions/devsprint-ana-nogal-1/DeliveryApp/Screens/Home/HomeViewController.swift
> +        navigationItem.title = "Delivery App"
corrigido.

2022-04-27 14:37 UTC, ananogal approved these changes

2022-04-27 15:02 UTC, merged